version: '3.8'

services:
  registros_frontend:
    build: .
    container_name: registros_frontend
    restart: always
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "80:80"
    env_file:
      - .env